---
- name: Determine artifact version
  set_fact:
    artifact_version: "{{ artifact.version | default('HEAD') }}"
    artifact_composer_install: []

- name: Determine target file
  set_fact:
    artifact_target_file: "{{ phpartifact_archivedir }}/{{ artifact_version }}.tgz"

- name: Check if the target file exists
  stat:
    path: "{{ artifact_target_file }}"
  register: artifact_target_file_stat

- import_tasks: ./phpartifact-build.yml
  when: artifact_target_file_stat.stat.exists == False or (artifact.force is defined and artifact.force == "yes")
